NAME		=	test

CPP			=	c++

CPPFLAGS	=	-Wall -Wextra -Werror -std=c++98

SRCS		=	Account.cpp \
				test.cpp

OBJS		=	$(SRCS:%.cpp=%.o)


all:		$(NAME)

$(NAME):	$(OBJS)
			$(CPP) $(CPPFLAGS) $(OBJS) -o $(NAME)

%.o:%.cpp
	 		$(CPP) $(CPPFLAGS) -c $< -o $@

clean:
			rm -rf $(OBJS)

fclean: 	clean
			rm -rf $(NAME)

re: 		fclean all

.PHONY:		all clean fclean re
